version: "3.9"

services:
  cypress:
    image: cypress/included:12.5.1
    environment:
      - CYPRESS_TG_API_KEY=$TG_API_KEY
    working_dir: /e2e
    volumes:
      - ./cypress.config.js:/e2e/cypress.config.js
      - ./cypress:/e2e/cypress