name: CI/CD
on: [pull_request, push]
jobs:
  test:
    runs-on: ubuntu-20.04
    environment: Production
    env:
      TG_API_KEY: ${{ secrets.TG_API_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Check API key
        run: echo $TG_API_KEY | awk '{print length}'

      - name: Find slots
        run: docker compose up --exit-code-from cypress

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: artifacts
          path: |
            cypress/videos/
            cypress/screenshots/